# Generated by Django 5.0.4 on 2024-04-17 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_photography_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='photographys_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
