# Generated by Django 5.0.4 on 2024-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_photography_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
